version: '3.8'

services:
  brikolog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brikolog_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - ./:/brikolog
    depends_on:
      - db
  db:
    image: postgres:15.3
    container_name: brikolog_db
    expose:
      - "5432"
    env_file:
      - .env.docker
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
volumes:
  db_data: